In [1]:
# Author: Prashant Shinde
# Reference: https://www.youtube.com/watch?v=kft1AJ9WVDk

In [2]:
# Goal: Build a Neural Network (Forward + Back prop) using NumPy

In [3]:
import numpy as np

In [4]:
print('A: Forward Propogation')
# Sequence: input -> (optimize) synapses -> neuron -> output 

A: Forward Propogation


In [5]:
# Define Normalizing function: Sigmoid
def sigmoid(x):
    return 1/(1 + np.exp(-x))


In [6]:
# Input data (4x3 matrics): 4 examples & 3 inputs
training_inputs = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]
                           ])

# Output data (4x1 matrics): 4 examples & 1 output
training_outputs = np.array([[0,1,1,0]]).T

print('Training Input:\n', training_inputs)
print('Training Output: \n', training_outputs)

Training Input:
 [[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]
Training Output: 
 [[0]
 [1]
 [1]
 [0]]


In [7]:
# Initialise weights
np.random.seed(1)

# 3 weights (w1, w2, w3) becasue we have 3 inputs / synapses
# Use random values from -1 to +1 with mean = 0
synaptic_weights = 2 * np.random.random((3,1)) - 1
print('Random starting synaptic weights:\n', synaptic_weights)    
print('Mean of synaptic weights:', synaptic_weights.mean())

Random starting synaptic weights:
 [[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Mean of synaptic weights: -0.24169275135861534


In [8]:
#Forward PATH only (Terrible prediction results)
for iteration in range(1):
    
    input_layer = training_inputs
    
    weights = synaptic_weights
    
    outputs = sigmoid(np.dot(input_layer, weights))
    
print('Output after training: \n', outputs)
print('BUT Expected output: \n', training_outputs)

Output after training: 
 [[0.2689864 ]
 [0.3262757 ]
 [0.23762817]
 [0.36375058]]
BUT Expected output: 
 [[0]
 [1]
 [1]
 [0]]


In [9]:
print('B: Backward Propogation')

B: Backward Propogation


In [10]:
print('We have to build a BACKPROPOGATION path to update weights based on PREDICTION ERROR')
print('Backpropogation key: Error weighted derivatives')

# To get CORRECT OUTPUT (/learn):
# Get initial predictions using randomly initialised weights: DONE
# Calculate Error =  Actual - Predicted output
# Derivatives: Adjust weights based on severeness of the error: Error weighted derivatives
# Repeat this process thousands of time

print('Adjust weights by = error * input * (Gradient of sigmoid function at predicted output)')
print('Weight adjustment is proportional to size of the error')

# If output if very large or very small meaning neuron is confident (confident neuron = no adjustment needed)


We have to build a BACKPROPOGATION path to update weights based on PREDICTION ERROR
Backpropogation key: Error weighted derivatives
Adjust weights by = error * input * (Gradient of sigmoid function at predicted output)
Weight adjustment is proportional to size of the error


In [11]:
# To adjust weights in backpropogation (Error weighted derivatives)
def sigmoid_derivative(output):
    return output * (1 - output)

In [12]:
for iteration in range(20000):
    
    # Forward propogation starts ...
    input_layer = training_inputs
    
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    #print('Output is:\n', outputs)
    #print('training_outputs is: \n', training_outputs)
    
    # Backpropogation starts ... 
    # calculate error
    error = training_outputs - outputs
    #print('error is:\n', error)
    
    # calculate adjustment based on error (high, low)
    adjustments = error * sigmoid_derivative(outputs)
    #print('adjustments are: \n', adjustments)
    
    # update weights
    synaptic_weights += np.dot(input_layer.T, adjustments)
    # synaptic_weights = synaptic_weights + np.dot(input_layer.T, adjustments)


print('synaptic_weights After training: \n', synaptic_weights)
print('Output after training: \n', outputs)
print('AND Expected output: \n', training_outputs)

synaptic_weights After training: 
 [[10.38040701]
 [-0.20641179]
 [-4.98452047]]
Output after training: 
 [[0.00679672]
 [0.99445583]
 [0.99548516]
 [0.00553614]]
AND Expected output: 
 [[0]
 [1]
 [1]
 [0]]


In [13]:
# More about Backpropogation (backprop) 


In [ ]:
# More about Activation Functions
