In [1]:
#Author: Prashant Shinde
#Date: March 9th, 2020

In [2]:
#Import NumPy
import numpy as np
import time

# Array Creation (np.array())

In [3]:
#NumPy Array
array_a = np.array([1,2,3,4,5])
print(array_a)
print(array_a.shape) #tuple - 1 dimentional array with shape 5

[1 2 3 4 5]
(5,)


In [4]:
#Python List
print([1,2,3,4,5])

[1, 2, 3, 4, 5]


In [5]:
#2 dimensional array
array_b = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(array_b)
print(array_b.shape) 

[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)


In [6]:
#create 3x3 numpy array (INT dtype)
seq_a = [1,2,3]
seq_b = [4,5,6]
seq_c = [7,8,9]

array_abc = np.array([seq_a,seq_b,seq_c])
print('3 dimetional NumPy array shape is:', array_abc.shape)
print(array_abc)

3 dimetional NumPy array shape is: (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
#create 3x3 numpy array (float dtype)
seq_a = [1,2,3]
seq_b = [4,5,6]
seq_c = [7,8,9]
seq_d = [10.0,11.0,12.0] #due to adding floats, all other NumPy array values will become float

array_abcd = np.array([seq_a,seq_b,seq_c, seq_d])
print('4 dimemsional NumPy array shape is:', array_abcd.shape)
print(array_abcd)

4 dimemsional NumPy array shape is: (4, 3)
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [8]:
#Numpy Array of 5 dimention (e.g: 5x2)
seq_5d = np.array([[1,2], 
                   [3,4],
                   [5,6],
                   [7,8],
                   [9,10]])
print('Shape of seq_5d is:', seq_5d.shape)
print(seq_5d)
print(type(seq_5d))


Shape of seq_5d is: (5, 2)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
<class 'numpy.ndarray'>


# Reshaping Array

In [9]:
array_a = np.array([[1,2,3],[4,5,6]])
print('SHAPE of NumPy array array_a is:', array_a.shape)
print('SIZE of NumPy array array_a is:', array_a.size)
array_a
#SIZE=6 means, there are 6 elements in the given NumPy array
#If you RESHAPE the NumPy array, SIZE should be SAME
#An NumPy array can be reshared in MANY ways (has to be a MULTIPLE of 2 numbers)

SHAPE of NumPy array array_a is: (2, 3)
SIZE of NumPy array array_a is: 6


array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
#Lets reshape 6 element NumPy array
# 6 = 1x6 or 3x2
#array_b = array_a.reshape(2,3) #(2,3) IS A TRANSPOSE OF (3,2)
#or
array_b = array_a.T
print('SAHPE is:', array_b.shape)
print('SIZE is:', array_b.size)
array_b

SAHPE is: (3, 2)
SIZE is: 6


array([[1, 4],
       [2, 5],
       [3, 6]])

In [11]:
#Lets reshape 6 element NumPy array
# 6 = 1x6 or 3x2
array_b = array_a.reshape(1,6)
print('SAHPE is:', array_b.shape)
print('SIZE is:', array_b.size)
array_b

SAHPE is: (1, 6)
SIZE is: 6


array([[1, 2, 3, 4, 5, 6]])

In [12]:
#Lets reshape 6 element NumPy array
# 6 = 1x6 or 3x2
array_b = array_a.reshape(6,1)
print('SAHPE is:', array_b.shape)
print('SIZE is:', array_b.size)
array_b

SAHPE is: (6, 1)
SIZE is: 6


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# Array Indexing

In [13]:
#Numpy INDEX starts from 0
#pull a value of NumPy array at specific index: Indexing

array_a = np.array([[1,2],[3,4],[5,6]])
array_a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
#Index 1 
array_a[1] #return a ROW

array([3, 4])

In [15]:
#Return a COLUMN (all rows)
array_a[:,1]

array([2, 4, 6])

In [16]:
#Return a specific VALUE
array_a[2,1]

6

In [17]:
#QUIZ:
array_a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
array_b = array_a.T
print('NumPy array_a is: \n', array_a)
print('Transposed NumPy array_b is: \n', array_b)

NumPy array_a is: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transposed NumPy array_b is: 
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [18]:
print('SHAPE of array_a is:', array_a.shape) #4 rows & 4 columns
print('SIZE of array_a is:', array_a.size) #16 elements in array
#Reshaping: can be done is - (1,16), (16,1 same as 1,16), (2,8), (8,2), (4,4 is a Transpose)

SHAPE of array_a is: (4, 4)
SIZE of array_a is: 16


In [19]:
array_b = array_a.reshape(2,8)
array_b

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [20]:
array_b = array_a.reshape(8,2)
array_b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [21]:
print('array_a is:\n', array_a)
print('\n', array_a[0])
print('\n', array_a[0,3], '&', array_a[3,1])

array_a is:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

 [1 2 3 4]

 4 & 14


In [22]:
#NumPy suppports NEGATIVE indexing like Python
print(array_a[-1])
print(array_a[0,-1])
print(array_a[-2,-3])
print(array_a[2,-3])
print(array_a[0,-3])
print(array_a[:,-2])


[13 14 15 16]
4
10
10
2
[ 3  7 11 15]


# Default Arrays

In [23]:
#int: (- to +) integer values
#uint: (+) integer values only

array_a = np.array([[1,2,3], [4,5,6]], dtype = float)
array_a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [24]:
array_b = np.zeros((3,3)) #takes 1 argument: TUPLE Shape
array_b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
array_c = np.ones((2,3))  #takes 1 argument: TUPLE Shape
array_c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
array_d = np.full((4,4), 7) #takes 2 arguments: TUPLE Shape & Value
array_d

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [27]:
array_e = np.random.random((3,3)) #takes 1 argument: TUPLE Shape
array_e

array([[0.11860988, 0.44804214, 0.67638369],
       [0.11633189, 0.1681891 , 0.04665667],
       [0.93452629, 0.60501851, 0.51979195]])

# NumPy Datatypes & Values

In [28]:
#If datatype is not specified, Numpy will use CORRECT DATATYPE automatically
#datatype np.int16 Integer (-32768 to 32767)
print(np.iinfo(np.int16).max)
print(np.iinfo(np.int16).min)

array_a = np.array([-32770])
print('type of array_a is:', array_a.dtype) #numpy handles dtype automatically based on element value

array_b = np.array([100])
print('type of array_b is:', array_b.dtype) #issue can be handled by defining dtype

array_c = np.array([100], dtype = np.int16)
print('type of array_c is:', array_c.dtype)


32767
-32768
type of array_a is: int64
type of array_b is: int64
type of array_c is: int16


In [29]:
#datatype np.int32 Integer
print(np.iinfo(np.int32).max)
print(np.iinfo(np.int32).min)

2147483647
-2147483648


In [30]:
#datatype np.int64 Integer
print(np.iinfo(np.int64).max)
print(np.iinfo(np.int64).min)

9223372036854775807
-9223372036854775808


In [31]:
#NumPy Datatype OVERFLOW
#-1 is converted into 65525 (due to datatype error: uint can only take +ve values)
array_overflow = np.array([-1,0,1], dtype = np.uint16)
array_overflow

#basically, we CAN overflow numpy array
#int16, int32 & int64 are all different (bit size allocation in the memory)


array([65535,     0,     1], dtype=uint16)

# Advanced Indexing

In [32]:
row1 = [1,2,3,4,5]
row2 = [6,7,8,9,10]
row3 = [11,12,13,14,15]
row4 = [16,17,18,19,20]
row5 = [21,22,23,24,25]

test_data = np.array([row1, row2, row3, row4, row5])
test_data


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [33]:
#Slice 
#Get 3rd & 4th value from each row

#don't do this
#print(test_data[:,2] ,'&', test_data[:,3])

print('\n', test_data[:,2:4:1]) #start:ending value:step size

#or using negative indexing
#print('\n',test_data[:,-3:-1:1])

#select same 2 columns using REVERSE 
print('\n', test_data[:,-2:-4:-1])


 [[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]

 [[ 4  3]
 [ 9  8]
 [14 13]
 [19 18]
 [24 23]]


In [34]:
#Boolean Indexing (True & False)
greater_than_5 = test_data > 5
print(greater_than_5)

#Return values as 1D array (values > 5)
print(test_data[greater_than_5])

[[False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [35]:
#Replace with 0 if element value is less than or equal to 5
drop_under_5 = np.where(test_data>5, test_data, 0)
print(drop_under_5)

[[ 0  0  0  0  0]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [36]:
#Replace with 0 if element value is GREATER than or equal to 5
drop_above_5 = np.where(test_data<5, test_data, 0)
print(drop_above_5)

[[1 2 3 4 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [37]:
#Logical AND 
drop_under_5_and_over_20 = np.logical_and(test_data>5,test_data<20 )
print(drop_under_5_and_over_20)

[[False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True False]
 [False False False False False]]


In [38]:
#print values between 5 and 20 from array
start = time.time()

test_data[np.logical_and(test_data>5,test_data<20)]

end = time.time()
total_time_numpy = end - start
print(total_time_numpy)


9.703636169433594e-05


In [39]:
#above operation using FOR loop 
start = time.time()

for i in test_data:
    for item in i:
        if item > 5 and item < 20:
            print(item)
            
end = time.time()
total_time_for_loop = end - start
print(total_time_for_loop)

6
7
8
9
10
11
12
13
14
15
16
17
18
19
0.0005087852478027344


In [40]:
#SPEED TEST (FOR LOOPS vs NumPy Array)
round(float((total_time_numpy/total_time_for_loop)*100), 2)
#NumPy operations resulted in ~20% faster operation than FOR loop

19.07

In [41]:
#Make all numpy elements negative
np.negative(test_data)

array([[ -1,  -2,  -3,  -4,  -5],
       [ -6,  -7,  -8,  -9, -10],
       [-11, -12, -13, -14, -15],
       [-16, -17, -18, -19, -20],
       [-21, -22, -23, -24, -25]])

In [42]:
#NumPy arange
array_a = np.arange(0,100,5)
print(array_a)
print('SHAPE:', array_a.shape)
print('SIZE:', array_a.size)

array_a_reshape = array_a.reshape(4,5) #(4,5) or (5,4) or (10,2) or (2,10) or (20,1) or (1,20)
print(array_a_reshape)


[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
SHAPE: (20,)
SIZE: 20
[[ 0  5 10 15 20]
 [25 30 35 40 45]
 [50 55 60 65 70]
 [75 80 85 90 95]]


In [43]:
#Negative Indexing (Last Column)
array_a_reshape[:,-1]

array([20, 45, 70, 95])

In [44]:
#Negative Indexing (Last Row)
array_a_reshape[-1,:]

array([75, 80, 85, 90, 95])

In [45]:
array_a_above_50 = array_a_reshape > 50
array_a_above_50


array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [46]:
#boolean Indexing
array_a_above_50 = array_a_reshape[array_a_reshape>50]
print(array_a_above_50)

#Python Slicing (SKIP every 1 number)
print(array_a_above_50[0:len(array_a_above_50):2])

#Python Slicing (SKIP every 2 numbers in between)
print(array_a_above_50[0:len(array_a_above_50):3] )

#To do above operation with FOR loop use modulo opration.
#Find the remainder after division of one number by another


[55 60 65 70 75 80 85 90 95]
[55 65 75 85 95]
[55 70 85]


In [47]:
#NumPy 'where' method
print(array_a_reshape)
print(np.where(array_a_reshape>50, array_a_reshape/2, -1))

[[ 0  5 10 15 20]
 [25 30 35 40 45]
 [50 55 60 65 70]
 [75 80 85 90 95]]
[[-1.  -1.  -1.  -1.  -1. ]
 [-1.  -1.  -1.  -1.  -1. ]
 [-1.  27.5 30.  32.5 35. ]
 [37.5 40.  42.5 45.  47.5]]


In [48]:
print(test_data)
print('LENGTH:', len(test_data))
print('SIZE:', test_data.size)
print('SHAPE:', test_data.shape)

#Array Slicing (remove columns)
print(test_data[:,0:5:2])
#OR
print(test_data[:,0:len(test_data):2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
LENGTH: 5
SIZE: 25
SHAPE: (5, 5)
[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]
[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]


# Reverse Array Elements (lr, ud & Negative Indexing)

In [49]:
#Reverse array elements
print('Original: \n', array_a_reshape)

#FLIP ROWS: First ROW becomes LAST row, etc 
print('Reversed ROWS: using -ve indexing \n', array_a_reshape[::-1])
#OR
#FLIP ROWS: First ROW becomes LAST ROW, etc
print('Reversed ROWS: using ud \n', np.flipud(array_a_reshape)) #ud: UP to DOWN

#FLIP COLUMNS: First COLUMN becomes LAST COLUMN, etc
print('Reversed COLUMNS: using lr \n', np.fliplr(array_a_reshape)) #lr: LEFT to RIGHT

#Using NEGATIVE Indexing
print('FLIP COLUMNS: using -ve Indexing: \n', array_a_reshape[:,-1:-6:-1])

Original: 
 [[ 0  5 10 15 20]
 [25 30 35 40 45]
 [50 55 60 65 70]
 [75 80 85 90 95]]
Reversed ROWS: using -ve indexing 
 [[75 80 85 90 95]
 [50 55 60 65 70]
 [25 30 35 40 45]
 [ 0  5 10 15 20]]
Reversed ROWS: using ud 
 [[75 80 85 90 95]
 [50 55 60 65 70]
 [25 30 35 40 45]
 [ 0  5 10 15 20]]
Reversed COLUMNS: using lr 
 [[20 15 10  5  0]
 [45 40 35 30 25]
 [70 65 60 55 50]
 [95 90 85 80 75]]
FLIP COLUMNS: using -ve Indexing: 
 [[20 15 10  5  0]
 [45 40 35 30 25]
 [70 65 60 55 50]
 [95 90 85 80 75]]


In [50]:
#FLIP BOTH ROWS & COLUMNS at the same time
print(array_a_reshape)
print('Reversed ROWS: using FLIP \n', np.flip(array_a_reshape)) #FLIP


[[ 0  5 10 15 20]
 [25 30 35 40 45]
 [50 55 60 65 70]
 [75 80 85 90 95]]
Reversed ROWS: using FLIP 
 [[95 90 85 80 75]
 [70 65 60 55 50]
 [45 40 35 30 25]
 [20 15 10  5  0]]


In [51]:
#NumPy logical_and
x = np.logical_and(array_a_reshape>20, array_a_reshape<75)
print(x)
print(array_a_reshape[x])


[[False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [False False False False False]]
[25 30 35 40 45 50 55 60 65 70]


# Array MATH

In [52]:
array_a = np.array([[1,2],[3,4]])
array_b = np.array([[5,6],[7,8]])

In [53]:
#Single Array MATH
print(array_a)
print(array_a.sum())
print('Axis 1:', array_a.sum(axis = 1)) #row
print('Axis 0:', array_a.sum(axis = 0)) #column
print(array_a.cumsum())
print(array_a.prod())
print(array_a.cumprod())

[[1 2]
 [3 4]]
10
Axis 1: [3 7]
Axis 0: [4 6]
[ 1  3  6 10]
24
[ 1  2  6 24]


In [54]:
print(array_a)
print(array_b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [55]:
#Multiple Array Math (element by element operation)
print(array_a + array_b)
print(array_a - array_b)
print(array_a * array_b)
print(array_a / array_b)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [56]:
#Vector Math (Matrics Multiplication: Not element wise )
print(np.dot(array_a, array_b))

[[19 22]
 [43 50]]


In [57]:
array_a = np.array([[1,2,3], [4,5,6], [7,8,9]])
array_b = np.array([[10,11,12],[13,14,15],[16,17,18]])
print(array_a)
print(array_b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [58]:
##Peak To Peak (difference or get a range)
print(array_a.ptp()) #9-1 (Max - Min)
print(array_b.ptp()) #18-10 (Max - Min)

8
8


In [59]:
print(array_a.ptp(axis = 1)) #(Max - Min) by each ROW
print(array_b.ptp(axis = 1)) #(Max - Min)

[2 2 2]
[2 2 2]


In [60]:
print(array_a.ptp(axis = 0)) #(Max - Min) by each COLUMN
print(array_b.ptp(axis = 0)) #(Max - Min)

[6 6 6]
[6 6 6]


In [61]:
print(array_a.min())
print(array_a.min(axis = 1))
print(array_a.min(axis = 0))

1
[1 4 7]
[1 2 3]


In [62]:
print(array_a.max())
print(array_a.max(axis = 1)) #row
print(array_a.max(axis = 0)) #column

9
[3 6 9]
[7 8 9]


In [63]:
print(array_a.mean())
print(array_a.mean(axis = 1)) #row
print(array_a.mean(axis = 0)) #column

5.0
[2. 5. 8.]
[4. 5. 6.]


In [64]:
print(array_a.sum())
print(array_a.size)
print('Mean = ', (array_a.sum())/(array_a.size) )

45
9
Mean =  5.0


In [65]:
#Power (base, exponent)
print(np.power(array_a, array_b))

[[                 1               2048             531441]
 [          67108864         6103515625       470184984576]
 [    33232930569601   2251799813685248 150094635296999121]]


In [66]:
array_a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
array_b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [68]:
array_c = np.array([[1,1,1],[2,2,2],[3,3,3]])
array_c

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [69]:
print(array_a * array_b * array_c)

[[ 10  22  36]
 [104 140 180]
 [336 408 486]]


# NumPy Broadcasting

In [70]:
#Allow us to do numerical operations using numpy array of DIFFERENT SIZES
#To do broadcasting, you need to have atleast same number of rows or columns between 2 arrays

In [71]:
array_a = np.array([[1,1,1,1], [2,2,2,2],[3,3,3,3]])
array_b = np.array([0,1,2,3])
array_c = np.array([[1],[2],[3]])
print(array_a)
print(array_b)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]
[0 1 2 3]


In [72]:
#broadcasting saves us time by not typing the same numbers again
print(array_a + array_b)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [73]:
#array b & d are SAME (broadcasting)
array_a = np.array([[1,1,1,1], [2,2,2,2],[3,3,3,3]])
array_b = np.array([0,1,2,3])
array_d = np.array([[0,1,2,3],[0,1,2,3],[0,1,2,3]])
print(array_a + array_d)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [74]:
print(array_a + array_c)

[[2 2 2 2]
 [4 4 4 4]
 [6 6 6 6]]


In [75]:
#Broadcasting 
#create a 5x5 array of value 1
array_1 = np.ones([5,5], dtype = np.int16)
print(array_1)

array_5 = np.array([1,2,3,4,5])
print(array_5)

print(array_1 * array_5)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[1 2 3 4 5]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
